- name: Install and configure zookeper
  hosts: zookeeper
  become: true
  user: ansible
  gather_facts: yes
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: preliminary
   - role: zookeeper
   - role: cleanup
