- name: Install and configure mesos
  hosts: slave
  become: true
  user: ansible
  gather_facts: yes
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: preliminary 
   - role: mesos-slave
