- name: Install and configure masters with consul
  hosts: masters
  become: true
  user: ansible
  gather_facts: no
  become_method: sudo
  vars_files:
   - group_vars/all
  roles:
   - role: zookeeper
   - role: mesos-master
   - role: marathon
   - role: consul-server
