---

- name: installing mesos slave
  apt:
   name: mesos 
   state: latest

- name: Disable the Mesos master service
  copy:
    content: "manual"
    dest: /etc/init/mesos-master.override

- name: Disable the zookeeper service
  copy:
    content: "manual"
    dest: /etc/init/zookeeper.override

- name: Set Mesos Slave ip
  copy:
   content: "{{slave_local_address}}"
   dest: /etc/mesos-slave/ip

- name: copying zk file to slave
  copy:
   content: "{{zookeeper_url}}"
   dest: /etc/mesos/zk

- name: Set Mesos slave hostname
  copy:
   content: "{{slave_local_address}}"
   dest: /etc/mesos-slave/hostname

- name: Insert/Update configuration block in /etc/mesos-slave/image_providers
  copy:
   content: DOCKER
   dest: /etc/mesos-slave/image_providers

- name: Insert/Update configuration block in /etc/mesos-slave/containerizers
  copy:
   content: docker,mesos
   dest: /etc/mesos-slave/containerizers

- name: Insert/Update configuration block in /etc/mesos-slave/isolation
  copy:
   content: filesystem/linux,docker/runtime
   dest: /etc/mesos-slave/isolation

- name: Install prerequisites
  apt:
   name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2' ,'software-properties-common']
   update_cache: yes

- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
   repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker
  apt:
   name: docker-ce
   update_cache: yes

- name: restart mesos
  service:
   name: mesos-slave
   state: restarted
